# curl -i -X POST -H 'Content-Type: application/json' -d '{"address":"mzY9avi4UUJBMgwuWvmBcEsNsSLKKxYGN5"}' http://localhost:8000/requestValidation
POST http://localhost:8000/requestValidation
Content-Type: application/json

{
  "address": "mzY9avi4UUJBMgwuWvmBcEsNsSLKKxYGN5"
}

###

